# Generated by Django 4.1.1 on 2022-11-03 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_images_image_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='their_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
