# Generated by Django 4.1.1 on 2022-11-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_liked_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='user_likes',
            field=models.ManyToManyField(related_name='user_liked', to='network.liked'),
        ),
    ]
