# Generated by Django 4.1.1 on 2022-11-03 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_posts_user_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user_likes',
        ),
    ]
