# Generated by Django 4.1.1 on 2022-11-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_remove_posts_user_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='user_likes',
            field=models.ManyToManyField(related_name='user_liked', to='network.liked'),
        ),
    ]
