# Generated by Django 4.1.1 on 2022-11-03 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_posts_user_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='posts',
            name='user_likes',
        ),
        migrations.DeleteModel(
            name='Liked',
        ),
        migrations.AddField(
            model_name='user_feed',
            name='posts',
            field=models.ManyToManyField(related_name='user_liked', to='network.posts'),
        ),
        migrations.AddField(
            model_name='user_feed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='their_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
