# Generated by Django 4.1.1 on 2022-11-14 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='followed',
        ),
        migrations.AddField(
            model_name='following',
            name='followed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followed', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
