# Generated by Django 4.1.1 on 2022-11-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_remove_following_followed_following_followed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='followed',
            field=models.IntegerField(default=0),
        ),
    ]
