# Generated by Django 4.1.1 on 2022-11-14 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_alter_following_followed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='followed',
        ),
        migrations.AddField(
            model_name='following',
            name='followed',
            field=models.ManyToManyField(related_name='thefollowed', to=settings.AUTH_USER_MODEL),
        ),
    ]
