# Generated by Django 4.1.1 on 2022-11-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_remove_following_followed_following_followed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='user',
        ),
        migrations.AddField(
            model_name='images',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
