# Generated by Django 4.1.1 on 2022-11-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_images_delete_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='network/files/userimages/default-avatar.jpg', upload_to='network/files/userimages'),
        ),
    ]
