# Generated by Django 4.1.1 on 2022-11-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_alter_user_image_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='user_profile',
            field=models.IntegerField(),
        ),
    ]
