# Generated by Django 4.1.1 on 2022-11-26 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_alter_profiles_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
