# Generated by Django 4.1.1 on 2022-12-01 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_remove_posts_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='network.posts'),
        ),
    ]
