# Generated by Django 4.1.1 on 2022-12-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0026_posts_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='parent',
            field=models.IntegerField(default=0),
        ),
    ]
