# Generated by Django 4.1.1 on 2022-12-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0028_user_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='banner',
            field=models.ImageField(default=1, upload_to='network/files/userimages'),
            preserve_default=False,
        ),
    ]
